import { StringAnyMap } from '../CommonTypes';

export interface ExistingUser {
  /**Context ID. Clients and developers must not pass this explicitly. This value is generated by the server and can be passed back by the worker SDKs.*/
  contextId?: string;
  /**User field for traceability of requests. Synchronous SDK APIs use this field for you.*/
  requestId?: string;
  /**User key within the realm ('login' field, by default)*/
  key: string;
}
